name: async_action
description: "A library for making asynchronous actions highly reactive to state changes in Flutter UI."
version: 1.0.0
homepage: https://github.com/LCostaN/async_actions
repository: https://github.com/LCostaN/async_actions
issue_tracker: https://github.com/LCostaN/async_actions/issues

topics:
  - async
  - state-management
  - ui-reactivity
  - flutter

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
